version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - rm -rf node_modules
      - npm ci

  build:
    commands:
      - echo "Building application"
      - npm run build

  post_build:
    commands:
      - aws s3 sync --delete dist s3://$S3_BUCKET_NAME
      - aws cloudfront create-invalidation --distribution-id $CF_ID --paths /index.html

artifacts:
  base-directory: dist
  files:
    - '**/*'

cache:
  paths:
    - ~/.npm/**/*